services:
    Synolia\Bundle\PokemonBundle\Command\PokemonInformationCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Synolia\Bundle\PokemonBundle\Provider\PokemonTransport'
        tags:
            - { name: console.command }